name: melhoreslugares
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flat_list: ^0.1.14
  provider: ^6.0.0
  page_view_dot_indicator: ^2.1.0
  google_sign_in: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    #- lib/recursos/imagens/produto.jpeg
    #- lib/recursos/imagens/bar.png
    #- lib/recursos/imagens/5cont.jpg
    #- lib/recursos/imagens/5cont2.jpg
    #- lib/recursos/imagens/5cont3.jpg
    #- lib/recursos/imagens/avatar.png
    - lib/recursos/json/feed.json
    - lib/recursos/json/comentarios.json
    - lib/recursos/imagens/