version: '3.1'
services:
  produtos:
    image: marcas
    build: ./dockerfiles/servicos/
    hostname: produtos
    command: python /servico/servico.py
    ports:
      - 5001:5000
  comentarios:
    image: marcas
    build: ./dockerfiles/servicos/
    hostname: comentarios
    command: python /servico/servico.py
    ports:
      - 5002:5000
  likes:
    image: marcas
    build: ./dockerfiles/servicos/
    hostname: likes
    command: python /servico/servico.py
    ports:
      - 5003:5000
